image: maven:3-jdk-8

cache:
  paths:
    - .m2/repository

services:
  - docker:dind
  - mysql:latest

variables:
  MAVEN_CLI_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true --batch-mode --errors --fail-at-end"
  DOCKER_HOST: docker
  MYSQL_DATABASE: gr1d_test
  MYSQL_ROOT_PASSWORD: passw0rd
  DB_URL: mysql
  DB_PORT: 3306
  DB_NAME: gr1d_test
  DB_USER: root
  DB_PASSWORD: passw0rd

stages:
  - deploy

executeTests:
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS clean test -pl core'
    - 'mvn $MAVEN_CLI_OPTS clean test -pl web'
    - 'mvn $MAVEN_CLI_OPTS clean test -pl datasource'

deployToArtifactory:
  stage: deploy
  script:
    - 'mvn $MAVEN_CLI_OPTS -Dmaven.test.skip=true -DupdateDependencies=false -s .ci/mvn_settings.xml clean deploy'
  only:
    - master
    - develop
